#
# Makefile for TI's shared transport line discipline
# and its protocol drivers (BT, FM, GPS)
#
obj-$(CONFIG_TI_ST_GYRO_L3G4200D) 		+= l3g4200d_gyr.o
obj-$(CONFIG_TI_ST_ACCEL_LIS3DH) 		+= lis3dh_acc.o
obj-$(CONFIG_CAP_PROX_SX9500_ZTE) += sx95xx.o sx9500.o
obj-$(CONFIG_SENSORS_ATTINY44A)         += attiny44a.o
obj-$(CONFIG_TI_ST_COMPASS_AK8963)		+= akm8963.o
obj-$(CONFIG_P865F02_GYRO_L3G4200D) 		+= l3g4200d_gyr.o
obj-$(CONFIG_P865F02_COMPASS_AK8963)		+= akm8963.o
