#
# Makefile for TI's shared transport line discipline
# and its protocol drivers (BT, FM, GPS)
#
obj-$(CONFIG_ZTE_SENSORS_KXTF9)			+=kxtik.o
# added by yangze 20120919
obj-$(CONFIG_ZTE_SENSORS_KIONIX)		+=kionix_accel.o
